### ISSUE TITLE
Syrup Village 3

### ISSUE THREAD

**Issue by galaxy9000** [galaxy9000/One-Pace#20]

**Comment by ivantuga2** [comment]
Timed episode: https://www.dropbox.com/s/pupmt6pkwur8ies/Kuro%203v4.regions_Halee.ass?dl=0

11:44, "It's not good enough of\Na reason for us to turn back.", I think the line should include "But" at the beginning.
23:29, "Hey! Never mind that,\NLuffy's trapped under there!", I believe it's "nevermind".

**Comment by Feeso6** [comment]
https://www.dropbox.com/s/cslg1cr7phhor0b/Kuro%203%20Final%20Halee.ass?dl=0 final subs

**Comment by ivantuga2** [comment]
Further comments:

I'd use a longer dash instead of two small ones (--). There should also be a space in-between the dashes and the text.
There should also be a space after each ellipsis (...), unless it's placed at the end of the line. Some lines in the script did have space after an ellipsis, while others didn't.
