### ISSUE TITLE
Dressrosa 46

### ISSUE THREAD

**Issue by galaxy9000** [galaxy9000/One-Pace#21]
QC File: https://www.dropbox.com/s/lw4eqvjj2a0efrh/%5BOne%20Pace%5D%5B794-795%5D%20Dressrosa%2046%20%5BQC%5D.mkv?dl=0

**Comment by Mr-Luffy** [comment]
@2:20  Cut or trim the flashback if possible.  Older episode clips or Episode of Sabo may substitute
@2:58  If possible, cut this unnecessary bit with Robin saying "Thanks"
@4:27  I don't suppose the flashback could start here?  Closer to where it starts in the manga.
@5:39  I suggest just showing his ship blow up like in the manga.  No shots of the crosshairs or the CD
@6:57 Seems like the Ivankov scene where he shock's Sabo can be bypassed.  Though to avoid an abrupt cut, I suggest holding the frame of Sabo's eye closed for a bit to give the indication that he just woke up and holding a few more before he says "huh"?  Otherwise I'm stuck with my "Ivankov gave Sabo amnesia" head-canon
@13:51-15:11  I wish there was a way to cut this, and maybe there is a way.  Sabo's canon line at the end must be retained.
@15:20  May be possible to remove that filler Barto/Luffy dialogue before Sabo shows up.  The particular clip of Sabo telling Luffy he can't have the fruit and Barto ambushing him, plus some banter there is depicted in Episode of Sabo faithfully, so the music track may merge better and save time.  I understand if it's not worth the effort
@23:38-24:00 Should be mostly cut.  Yes, there is that shot of the trees, but everything else should go.  At the very least remove the scene where Caesar Clown is kicked in the balls by Sanji

**Comment by Feeso6** [comment]
5:01 Dragons face suddenly coming out of shadow looks really odd, like it's been sped up. I think just a still of his shocked face would work better

5:46 we don't see him talk in the manga so if you could end the sfx another way, try it

8:01 Zoro talking during the flashback effect is odd

8:34 I think this sounds like it was cut to mid sfx, add a fade if possible

8:44 black and sudden SFX stop, I don't think it really works, if this isn't raw Toei I think you could get away with just using the visuals and adding SFXs your self

10:16 something seems sudden about this, adjust if possible 

10:46 Sabo looks like he's about to take another breath before the flash back

10:51 music seems to kind of just stop without finishing 

14:25 The cut to Ace and White beard's graves seems a bit sudden, it'd be better if you stuck on Sabo for a tad longer

15:02 you're going to think I’m nuts but I think no sfx for him picking up the hat and pipe is slightly off as we get walking sfx afterwards

14:25-15:20 doesn’t seem to be in the manga unless I’m missing a page, OST doesn't seem to be an issue here tho so this should be fixable. Also, I thought Sabo already asked about getting the fruit? 

21:50 sounds like OST repeats a single beat twice here, sounds off

22:40 Toei probably didn't include but we're missing a "w-what"

25:36 OST just stops when the impact happens

30:24 fade out seems unnecessary, just freeze frame on the belt

**Comment by DavidENishball** [comment]
1:59 – The transition from the outside of the house to the inside is abrupt. There should be an establishing shot of the inside of the house before Robin speaks, or there should be some dialogue that plays before the camera enters the house, or we should see a character walking into the house.

8:17 -  This shot of Ace's photograph in the newspaper is extremely brief.  I also recommend re-ordering the scene.  First Sabo says “Ace helped me”, then we view the newspaper, then Sabo says “That's what I think anyways”, and then the shot of Zoro reacting.

[One Pace - Dressrosa 46 QC.pdf](https://github.com/galaxy9000/One-Pace/files/1083779/One.Pace.-.Dressrosa.46.QC.pdf)

**Comment by galaxy9000** [comment]
Graphics

DR46

Sabo's Adventure サボの冒険

http://2.bp.blogspot.com/-Crxu4emoWUs/WPCxhx1cpiI/AAAAAAAC_EE/lA5oeYuYMbUqTakTClg5jlUkt1upx_zpQCHM/s16000/0794-010.png
http://2.bp.blogspot.com/-c_j4O-KYJlI/WPCxxjORLEI/AAAAAAAC_GE/9I0LRx-OkS82B3xFVV3MX-5AqaIrHN1zwCHM/s16000/0795-002.png
http://2.bp.blogspot.com/-K4RYsjj1Rdg/WPCx0LdQIwI/AAAAAAAC_Gg/RKyx42bsocgM5LlsiHE0cAoQ-H0MeQZUACHM/s16000/0795-004.png 
(for this one, the "on the sunny" part should be excluded. Toei changed it a bit.
