### ISSUE TITLE
Syrup 04

### ISSUE THREAD

**Issue by Feeso6** [galaxy9000/One-Pace#22]
QC file: https://www.dropbox.com/s/tfcl0cqt4g6djck/Syrup%2004%20QC.mkv?dl=0

**Comment by Mr-Luffy** [comment]
@3:26  See if filler dialogue can be trimmed (see next)
@3:40  Padding can be removed.  If there is an issue with music timing, may I suggest including the Kuro clip where he says "If he should ever lay a hand on you...." during one of these parts?  Won't save time, but will be more faithful to the manga and remove unnecessary padding content
@13:31 Not sure if possible, but can the scared expressions of Butchie and Siam be restored?
@15:50 Restore the Jango line saying "There it is...The Pussyfoot Maneuver" though don't include Nami repeating it
@21:37 Nami should step on Luffy's face before turning around.  This is shown right before the commercial break, then given a different sequence afterward.  Music issues?
@22:11  Odd transition.  I suggest removing that black fade of Luffy blinking
@23:06-23:13 Cut this.  It's filler and reinterated by Nami right after
@28:06  Is it pissoble to have Kaya whip out that pistol faster during the following cut?

**Comment by Feeso6** [comment]
Luffy @326 and @3:40 fix: https://www.dropbox.com/s/y1sfo3aszhn2zeu/2017-06-23_05-18-09.mp4?dl=0

**Comment by galaxy9000** [comment]
Fixes

1:54 - The beat is a bit off for Desperate Situation. It needs to play for a few more ms before it switches to the episode OST.

1:57 - Put black here. Vegas blank black is different from actual black

2:15-2:25 I recommend starting the wind sfx a bit sooner.

2:42 - A bit of a continuity error. Her hand is in a different position.

3:40 - Dunno if http://2.bp.blogspot.com/-SWYSZxSPrVo/WBqEn818AhI/AAAAAAABX0E/khD5IIs5KrUAd5Mqykb2oSbRIIwr0BdhgCHM/s16000/0031-006.png was ever said
but if it was, try to fit it in if it has no music.

4:10 - Flashback effect or do a fade in here.

4:43 - I'd hold on the shot of the empty house for a second longer. The cut is a bit abrupt right now since he just finished speaking.

5:54 - The snoring shouldn't start while there is speech, nor on the previous frame.

5:58 - Snoring ends too abruptly, and he wakes up too fast. There's a second or two of footage before what you have that shows him still snoring
and then popping awake, so you should probably add that back.

6:22 - You can hear the remnant of the wind sfx at this cut.

6:52 - You should try to include Jango's "come forth, meowban brothers!" It's a bit less sudden than them just jumping out, and it's canon.
http://i.imgur.com/o29CwJJ.png

7:26 - The music cut here is very rough. Doesn't fit the beat at all. Sounds odd too.

7:31 - Same with the cut here. It's like a "slowed" fade in of the next portion, and just doesn't work.

7:40  - The cut here is barely off. The previous piano bit doesn't "finish".

General for these 3 cuts - You seem to have enough time to just let the OST play out.

16:46 - Add back this panel - http://i.imgur.com/YGJso2U.png It can be seen right after Jango in the episode.

19:54 - Audio click here.

21:24 - You cut Jango's full line. He continues it in the next shot.

21:28 - Add a fade or something here for Jango's ring.

21:33 - Add back the scene with the ring flying. The sfx just suddenly ends as it is.

22:55 - Try to finish the OST. This is very lazy from Toei.

30:18 - Bullet sfx can be heard at the cut. I suggest readding it.

**Comment by DavidENishball** [comment]
https://www.dropbox.com/s/tfcl0cqt4g6djck/Syrup%2004%20QC.mkv?dl=0
[One Pace - Kuro 4 QC.pdf](https://github.com/galaxy9000/One-Pace/files/1111120/One.Pace.-.Kuro.4.QC.pdf)


1:56 – The intro to the episode needs more of an establishing shot of Kaya's house, both for pacing and
to better match the manga.
1:57 – Remove or replace this fade to black. The two shots it connects are directly related and need no
bridging.
2:19 – If possible, make the cut between Usopp stabbing the sword and Kaya waking up more sudden.
3:19 – Hold on Kaya's reaction to the shocking news a little longer. To make room, eat into the
following shot of Merry's face, as there's a little too much time of him not talking.
3:28 to 3:36 – This single shot of Kaya covering her mouth is really long with nothing happening. Is
there some more interesting footage we could see during this part of the dialogue? She also have some
kind of facial change when she starts talking.
3:41 – What is the purpose of this shot of the exterior window? It doesn't add anything to the scene. I
suggest removing or replacing it, or using it as an intro to some other environmental shots.
3:51 – This is the same shot of Kaya covering her mouth that we've seen for 15 seconds now. Please
replace it with something more dynamic, or replace earlier uses of it.
3:55 – This shot of Merry lying on the floor is repeated from earlier, and doesn't add anything to the
scene. Please remove it.
06:53 – This cut to the prow of the ship and the two pirates warping away needs more lead in and
establishing shot, especially since we are completely changing location.
In the manga, before the brothers appear they are called by Django, and there is some dialog between
Zoro and Luffy wondering about the new opponents about to appear. This is not in the current edit.
8:39 – We need to linger on Zoro a little longer after he looks for his swords, so we have a change to
register they're missing. We should also follow it with a shot that clearly shows that Siam has the
swords.
Also, in the Manga, right before Zoro looks for his swords, there is some commentary from Usopp and
Nami. This is not present in the current edit.
18:01 – Zoro's line “H-hey, you! Now you're kicking my swords, too?!” is unclear about what he
means by “too”. He should explicitly mention that she trampled him earlier.
21:25 – This shot of Nami running past the Black Cat pirates is way too brief. Lengthen it or provide
some other establishing shots of where Nami is.

**Comment by Feeso6** [comment]
Grug's Fixes

3:19- https://www.dropbox.com/s/y3vqitrzkyx7vr9/2017-07-01_03-43-09.mp4?dl=0

3:55- will fix is Raw's rainbow flicker can be resolved 

6:53- https://www.dropbox.com/s/f6lbntqkdcj4kd4/2017-07-01_01-44-39.mp4?dl=0 

18:01- changed to "now" in Aegis 

21:25- https://www.dropbox.com/s/r3z4nok9wd8cm4r/2017-07-01_00-41-09.mp4?dl=0

**Comment by Feeso6** [comment]
Time File: https://www.dropbox.com/s/wrwddrjw3wbt8js/Syrup%20Village%2004%20Time.mkv?dl=0

Ass file: https://www.dropbox.com/s/q9gz697xcp9nbhk/Syrup%20Village%2004.regions.ass?dl=0
